"""Versioned domain contracts for Markeitech."""

from markeitech.domain.classification import classify_trade, classify_trade_with_quote_history
from markeitech.domain.events import (
    ActiveInstrumentChangedEvent,
    GatewayEvent,
    GatewayEventType,
    StrategyState,
    StrategyStateEvent,
)
from markeitech.domain.instruments import (
    AggressionOutcomeConfig,
    AnalysisProfile,
    CryptoContractConfig,
    EquityLikeContractConfig,
    FuturesContractConfig,
    InstrumentContractConfig,
    InstrumentDataMode,
    InstrumentRegistryConfig,
    InstrumentRole,
    InstrumentRuntimeConfig,
    InstrumentWarmupConfig,
    NQContractConfig,
    SecurityType,
    SessionProfile,
    WarmupTimeframe,
)
from markeitech.domain.market_data import (
    BarInterval,
    CanonicalQuoteTick,
    CanonicalTradeTick,
    ClassifiedTrade,
    OneMinuteBar,
    TradeSide,
)
from markeitech.domain.state import (
    GapSeverity,
    GapState,
    ReadinessState,
    ReadinessStatus,
    SourceHealth,
    SourceStatus,
)

__all__ = [
    "AggressionOutcomeConfig",
    "BarInterval",
    "ActiveInstrumentChangedEvent",
    "AnalysisProfile",
    "CanonicalQuoteTick",
    "CanonicalTradeTick",
    "ClassifiedTrade",
    "CryptoContractConfig",
    "EquityLikeContractConfig",
    "FuturesContractConfig",
    "GapSeverity",
    "GapState",
    "GatewayEvent",
    "GatewayEventType",
    "InstrumentContractConfig",
    "InstrumentDataMode",
    "InstrumentRegistryConfig",
    "InstrumentRole",
    "InstrumentRuntimeConfig",
    "InstrumentWarmupConfig",
    "NQContractConfig",
    "OneMinuteBar",
    "ReadinessState",
    "ReadinessStatus",
    "SecurityType",
    "SessionProfile",
    "SourceHealth",
    "SourceStatus",
    "StrategyState",
    "StrategyStateEvent",
    "TradeSide",
    "WarmupTimeframe",
    "classify_trade",
    "classify_trade_with_quote_history",
]
