"""Deterministic signal contracts and lifecycle rules."""

from markeitech.signals.aggression import (
    AggressionEvaluation,
    AggressionEvaluationStatus,
    AggressionWindowSnapshot,
    evaluate_aggression_window,
    evaluate_bar_impulse_window,
)
from markeitech.signals.arming import (
    ArmedLocationSignal,
    build_armed_location_signal,
    invalidate_ended_location_signal,
    restore_location_episode,
)
from markeitech.signals.composition import (
    BoundedFeatureCommitHandoff,
    CommittedFeatureState,
    FeatureHandoffSnapshot,
    FeatureHandoffStatus,
)
from markeitech.signals.config import (
    AggressionPolicyConfig,
    LocationPolicyConfig,
    LocationSourcePolicyConfig,
    OpposingContextPolicy,
    SignalDefinitionConfig,
    SignalRuntimeConfig,
    intraday_context_definition,
)
from markeitech.signals.contracts import (
    LocationQualification,
    LocationQualificationStatus,
    LocationSourceKind,
    SignalConfirmationContext,
    SignalConfirmationMethod,
    SignalDirection,
    SignalEvidenceFidelity,
    SignalEvidenceReference,
    SignalEvidenceStage,
    SignalEvidenceType,
    SignalFamily,
    SignalLocationMatch,
    SignalLocationZone,
    SignalLocationZoneKind,
    SignalSnapshot,
    SignalStatus,
    SignalTransitionEvent,
    signal_setup_key,
)
from markeitech.signals.direction import (
    CommittedMarketContextBundle,
    DirectionCandidateDecision,
    DirectionQualification,
    DirectionQualificationStatus,
    DirectionRegimeTracker,
    qualify_direction,
)
from markeitech.signals.episode import (
    LocationEpisodeDecision,
    LocationEpisodeEventType,
    LocationEpisodeObservation,
    LocationEpisodeTracker,
    SignalLocationEpisode,
)
from markeitech.signals.lifecycle import transition_signal
from markeitech.signals.location import (
    LocationZoneDerivation,
    derive_location_zones,
    qualify_location,
)
from markeitech.signals.observations import (
    AggressionObservationStoreSnapshot,
    BoundedAggressionObservationStore,
)
from markeitech.signals.projection import (
    BoundedSignalProjectionWriter,
    SignalLifecycleProjection,
    SignalLifecycleProjectionKind,
    SignalOperatorProjection,
    SignalProjectionWriterSnapshot,
    SignalProjectionWriterStatus,
    SignalRuntimeProjection,
    SignalRuntimeProjectionKind,
    format_signal_operator_projection,
    signal_projection_color,
)
from markeitech.signals.runtime import (
    LiveSignalRuntime,
    LiveSignalRuntimeSnapshot,
    LiveSignalRuntimeStatus,
    SignalEvaluationEvent,
)

__all__ = [
    "AggressionEvaluation",
    "AggressionEvaluationStatus",
    "AggressionPolicyConfig",
    "AggressionWindowSnapshot",
    "AggressionObservationStoreSnapshot",
    "BoundedFeatureCommitHandoff",
    "BoundedAggressionObservationStore",
    "BoundedSignalProjectionWriter",
    "CommittedFeatureState",
    "FeatureHandoffSnapshot",
    "FeatureHandoffStatus",
    "LiveSignalRuntime",
    "LiveSignalRuntimeSnapshot",
    "LiveSignalRuntimeStatus",
    "SignalEvaluationEvent",
    "SignalLifecycleProjection",
    "SignalLifecycleProjectionKind",
    "SignalOperatorProjection",
    "SignalProjectionWriterSnapshot",
    "SignalProjectionWriterStatus",
    "SignalRuntimeProjection",
    "SignalRuntimeProjectionKind",
    "ArmedLocationSignal",
    "SignalDirection",
    "SignalConfirmationMethod",
    "SignalConfirmationContext",
    "CommittedMarketContextBundle",
    "DirectionCandidateDecision",
    "DirectionQualification",
    "DirectionQualificationStatus",
    "DirectionRegimeTracker",
    "LocationPolicyConfig",
    "LocationEpisodeDecision",
    "LocationEpisodeEventType",
    "LocationEpisodeObservation",
    "LocationEpisodeTracker",
    "LocationQualification",
    "LocationQualificationStatus",
    "LocationSourceKind",
    "LocationSourcePolicyConfig",
    "LocationZoneDerivation",
    "OpposingContextPolicy",
    "SignalDefinitionConfig",
    "SignalEvidenceFidelity",
    "SignalEvidenceReference",
    "SignalEvidenceStage",
    "SignalEvidenceType",
    "SignalFamily",
    "SignalLocationMatch",
    "SignalLocationEpisode",
    "SignalLocationZone",
    "SignalLocationZoneKind",
    "SignalSnapshot",
    "SignalRuntimeConfig",
    "SignalStatus",
    "SignalTransitionEvent",
    "signal_setup_key",
    "derive_location_zones",
    "evaluate_aggression_window",
    "evaluate_bar_impulse_window",
    "build_armed_location_signal",
    "invalidate_ended_location_signal",
    "qualify_direction",
    "qualify_location",
    "restore_location_episode",
    "intraday_context_definition",
    "transition_signal",
    "format_signal_operator_projection",
    "signal_projection_color",
]
