"""Deterministic signal contracts and lifecycle rules."""

from markeitech.signals.arming import (
    ArmedLocationSignal,
    build_armed_location_signal,
    invalidate_ended_location_signal,
    restore_location_episode,
)
from markeitech.signals.config import (
    LocationPolicyConfig,
    LocationSourcePolicyConfig,
    OpposingContextPolicy,
    SignalDefinitionConfig,
    SignalRuntimeConfig,
    intraday_context_definition,
)
from markeitech.signals.contracts import (
    LocationQualification,
    LocationQualificationStatus,
    LocationSourceKind,
    SignalDirection,
    SignalEvidenceFidelity,
    SignalEvidenceReference,
    SignalEvidenceStage,
    SignalEvidenceType,
    SignalFamily,
    SignalLocationMatch,
    SignalLocationZone,
    SignalLocationZoneKind,
    SignalSnapshot,
    SignalStatus,
    SignalTransitionEvent,
    signal_setup_key,
)
from markeitech.signals.direction import (
    CommittedMarketContextBundle,
    DirectionCandidateDecision,
    DirectionQualification,
    DirectionQualificationStatus,
    DirectionRegimeTracker,
    qualify_direction,
)
from markeitech.signals.episode import (
    LocationEpisodeDecision,
    LocationEpisodeEventType,
    LocationEpisodeObservation,
    LocationEpisodeTracker,
    SignalLocationEpisode,
)
from markeitech.signals.lifecycle import transition_signal
from markeitech.signals.location import (
    LocationZoneDerivation,
    derive_location_zones,
    qualify_location,
)

__all__ = [
    "ArmedLocationSignal",
    "SignalDirection",
    "CommittedMarketContextBundle",
    "DirectionCandidateDecision",
    "DirectionQualification",
    "DirectionQualificationStatus",
    "DirectionRegimeTracker",
    "LocationPolicyConfig",
    "LocationEpisodeDecision",
    "LocationEpisodeEventType",
    "LocationEpisodeObservation",
    "LocationEpisodeTracker",
    "LocationQualification",
    "LocationQualificationStatus",
    "LocationSourceKind",
    "LocationSourcePolicyConfig",
    "LocationZoneDerivation",
    "OpposingContextPolicy",
    "SignalDefinitionConfig",
    "SignalEvidenceFidelity",
    "SignalEvidenceReference",
    "SignalEvidenceStage",
    "SignalEvidenceType",
    "SignalFamily",
    "SignalLocationMatch",
    "SignalLocationEpisode",
    "SignalLocationZone",
    "SignalLocationZoneKind",
    "SignalSnapshot",
    "SignalRuntimeConfig",
    "SignalStatus",
    "SignalTransitionEvent",
    "signal_setup_key",
    "derive_location_zones",
    "build_armed_location_signal",
    "invalidate_ended_location_signal",
    "qualify_direction",
    "qualify_location",
    "restore_location_episode",
    "intraday_context_definition",
    "transition_signal",
]
